export type Role = "trainee" | "supervisor"
export type ComplianceStatus = "compliant" | "warning" | "violation"
export type ActivityCategory = "Restricted" | "Unrestricted" | "Supervision"
export type ActivityStatus = "confirmed" | "pending" | "rejected"

export const currentUser = {
  id: "u1",
  name: "Sarah Mitchell",
  email: "sarah.mitchell@email.com",
  role: "trainee" as Role,
  certType: "BCBA",
  fieldworkType: "Concentrated",
  supervisor: "Dr. Emily Rodriguez",
  initials: "SM",
  timezone: "America/Chicago",
}

export const supervisorUser = {
  id: "sup1",
  name: "Dr. Emily Rodriguez",
  email: "emily.rodriguez@behaviorgroup.com",
  role: "supervisor" as Role,
  certType: "BCBA-D",
  initials: "ER",
}

export const activities = [
  {
    id: "a1",
    title: "Discrete Trial Training",
    client: "Client A",
    date: "May 19, 2025",
    day: "Mon",
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    duration: 2,
    category: "Restricted" as ActivityCategory,
    subcategory: "Direct Therapy",
    supervisionRelated: false,
    directObservation: false,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "",
  },
  {
    id: "a2",
    title: "Behavior Reduction Program Review",
    client: "Client B",
    date: "May 19, 2025",
    day: "Mon",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Program Development",
    supervisionRelated: false,
    directObservation: false,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "",
  },
  {
    id: "a3",
    title: "Parent Training Session",
    client: "Client A",
    date: "May 18, 2025",
    day: "Sun",
    startTime: "3:00 PM",
    endTime: "4:30 PM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Training Delivery",
    supervisionRelated: false,
    directObservation: false,
    status: "pending" as ActivityStatus,
    supervisorApproved: false,
    notes: "Initial parent consultation — caregiver very engaged",
  },
  {
    id: "a4",
    title: "Supervision with Dr. Rodriguez",
    client: null,
    date: "May 17, 2025",
    day: "Sat",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    duration: 1,
    category: "Supervision" as ActivityCategory,
    subcategory: "Individual Supervision",
    supervisionRelated: true,
    directObservation: true,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "Monthly direct observation, reviewed skill programs",
  },
  {
    id: "a5",
    title: "Natural Environment Teaching",
    client: "Client C",
    date: "May 16, 2025",
    day: "Fri",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    duration: 2,
    category: "Restricted" as ActivityCategory,
    subcategory: "Direct Therapy",
    supervisionRelated: false,
    directObservation: false,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: false,
    notes: "",
  },
  {
    id: "a6",
    title: "Functional Behavior Assessment",
    client: "Client D",
    date: "May 15, 2025",
    day: "Thu",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    duration: 3,
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Assessment",
    supervisionRelated: false,
    directObservation: false,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "FBA for new client onboarding — indirect + direct methods",
  },
  {
    id: "a7",
    title: "RBT Supervision Session",
    client: null,
    date: "May 14, 2025",
    day: "Wed",
    startTime: "11:00 AM",
    endTime: "12:00 PM",
    duration: 1,
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Supervision Delivery",
    supervisionRelated: false,
    directObservation: true,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "",
  },
  {
    id: "a8",
    title: "Skill Acquisition Program Development",
    client: "Client B",
    date: "May 13, 2025",
    day: "Tue",
    startTime: "8:30 AM",
    endTime: "10:00 AM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Program Development",
    supervisionRelated: false,
    directObservation: false,
    status: "confirmed" as ActivityStatus,
    supervisorApproved: true,
    notes: "",
  },
]

export const weeklyActivities = [
  {
    id: "w1",
    title: "Discrete Trial Training — Client A",
    date: "May 19",
    day: "Mon",
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    duration: 2,
    category: "Restricted" as ActivityCategory,
    source: "calendar" as "calendar" | "manual",
    confirmed: false,
  },
  {
    id: "w2",
    title: "Behavior Program Review",
    date: "May 19",
    day: "Mon",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    source: "calendar" as "calendar" | "manual",
    confirmed: false,
  },
  {
    id: "w3",
    title: "NET — Community Skills (Client C)",
    date: "May 20",
    day: "Tue",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    duration: 2,
    category: "Restricted" as ActivityCategory,
    source: "calendar" as "calendar" | "manual",
    confirmed: true,
  },
  {
    id: "w4",
    title: "Parent Training — Client A",
    date: "May 21",
    day: "Wed",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    source: "calendar" as "calendar" | "manual",
    confirmed: true,
  },
  {
    id: "w5",
    title: "Supervision with Dr. Rodriguez",
    date: "May 22",
    day: "Thu",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    duration: 1,
    category: "Supervision" as ActivityCategory,
    source: "calendar" as "calendar" | "manual",
    confirmed: false,
  },
  {
    id: "w6",
    title: "Data Analysis & Graphing",
    date: "May 23",
    day: "Fri",
    startTime: "8:00 AM",
    endTime: "9:30 AM",
    duration: 1.5,
    category: "Unrestricted" as ActivityCategory,
    source: "manual" as "calendar" | "manual",
    confirmed: false,
  },
]

export const templates = [
  {
    id: "t1",
    title: "Monday / Wednesday / Friday DTT",
    category: "Restricted" as ActivityCategory,
    subcategory: "Direct Therapy",
    days: ["Mon", "Wed", "Fri"],
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    duration: 2,
    client: "Client A",
    active: true,
    nextOccurrence: "Mon, May 19",
    weeklyHours: 6,
  },
  {
    id: "t2",
    title: "Tuesday / Thursday NET",
    category: "Restricted" as ActivityCategory,
    subcategory: "Direct Therapy",
    days: ["Tue", "Thu"],
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    duration: 2,
    client: "Client C",
    active: true,
    nextOccurrence: "Tue, May 20",
    weeklyHours: 4,
  },
  {
    id: "t3",
    title: "Wednesday Parent Training",
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Training Delivery",
    days: ["Wed"],
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    duration: 1.5,
    client: "Client A",
    active: true,
    nextOccurrence: "Wed, May 21",
    weeklyHours: 1.5,
  },
  {
    id: "t4",
    title: "Thursday Supervision",
    category: "Supervision" as ActivityCategory,
    subcategory: "Individual Supervision",
    days: ["Thu"],
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    duration: 1,
    client: null,
    active: true,
    nextOccurrence: "Thu, May 22",
    weeklyHours: 1,
  },
  {
    id: "t5",
    title: "Friday Morning Data Review",
    category: "Unrestricted" as ActivityCategory,
    subcategory: "Data Analysis",
    days: ["Fri"],
    startTime: "8:00 AM",
    endTime: "9:30 AM",
    duration: 1.5,
    client: null,
    active: false,
    nextOccurrence: null,
    weeklyHours: 1.5,
  },
]

export const monthlyReports = [
  {
    id: "r1",
    month: "May 2025",
    slug: "may-2025",
    totalHours: 42.5,
    restrictedHours: 18,
    unrestrictedHours: 20,
    supervisionHours: 4.5,
    restrictedPercent: 42.4,
    supervisionPercent: 10.6,
    complianceStatus: "compliant" as ComplianceStatus,
    supervisorSigned: false,
    generatedPdf: false,
    inProgress: true,
  },
  {
    id: "r2",
    month: "April 2025",
    slug: "apr-2025",
    totalHours: 38,
    restrictedHours: 16,
    unrestrictedHours: 18,
    supervisionHours: 4,
    restrictedPercent: 42.1,
    supervisionPercent: 10.5,
    complianceStatus: "compliant" as ComplianceStatus,
    supervisorSigned: true,
    generatedPdf: true,
    inProgress: false,
  },
  {
    id: "r3",
    month: "March 2025",
    slug: "mar-2025",
    totalHours: 35,
    restrictedHours: 19,
    unrestrictedHours: 13,
    supervisionHours: 3,
    restrictedPercent: 54.3,
    supervisionPercent: 8.6,
    complianceStatus: "warning" as ComplianceStatus,
    supervisorSigned: true,
    generatedPdf: true,
    inProgress: false,
  },
  {
    id: "r4",
    month: "February 2025",
    slug: "feb-2025",
    totalHours: 40,
    restrictedHours: 17,
    unrestrictedHours: 19,
    supervisionHours: 4,
    restrictedPercent: 42.5,
    supervisionPercent: 10.0,
    complianceStatus: "compliant" as ComplianceStatus,
    supervisorSigned: true,
    generatedPdf: true,
    inProgress: false,
  },
  {
    id: "r5",
    month: "January 2025",
    slug: "jan-2025",
    totalHours: 32,
    restrictedHours: 13,
    unrestrictedHours: 16,
    supervisionHours: 3,
    restrictedPercent: 40.6,
    supervisionPercent: 9.4,
    complianceStatus: "compliant" as ComplianceStatus,
    supervisorSigned: true,
    generatedPdf: true,
    inProgress: false,
  },
]

export const supervisees = [
  {
    id: "sup-s1",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@email.com",
    initials: "SM",
    certType: "BCBA",
    fieldworkType: "Concentrated",
    totalHours: 423.5,
    targetHours: 1000,
    restrictedPercent: 43.2,
    supervisionPercent: 10.8,
    complianceStatus: "compliant" as ComplianceStatus,
    pendingApprovals: 1,
    lastActivity: "May 19, 2025",
    monthlyHours: 42.5,
    startDate: "Jan 2025",
  },
  {
    id: "sup-s2",
    name: "Marcus Chen",
    email: "marcus.chen@email.com",
    initials: "MC",
    certType: "BCBA",
    fieldworkType: "Concentrated",
    totalHours: 287,
    targetHours: 1000,
    restrictedPercent: 55.8,
    supervisionPercent: 9.2,
    complianceStatus: "warning" as ComplianceStatus,
    pendingApprovals: 2,
    lastActivity: "May 18, 2025",
    monthlyHours: 28,
    startDate: "Feb 2025",
  },
  {
    id: "sup-s3",
    name: "Aisha Johnson",
    email: "aisha.johnson@email.com",
    initials: "AJ",
    certType: "BCBA",
    fieldworkType: "Unrestricted",
    totalHours: 156.5,
    targetHours: 1500,
    restrictedPercent: 0,
    supervisionPercent: 11.5,
    complianceStatus: "compliant" as ComplianceStatus,
    pendingApprovals: 0,
    lastActivity: "May 17, 2025",
    monthlyHours: 18,
    startDate: "Mar 2025",
  },
]

export const approvalQueue = [
  {
    id: "aq1",
    supervisee: "Sarah Mitchell",
    superviseeId: "sup-s1",
    initials: "SM",
    weekOf: "May 13–17, 2025",
    totalHours: 10.5,
    activitiesCount: 6,
    restrictedHours: 4,
    unrestrictedHours: 5.5,
    supervisionHours: 1,
    status: "pending" as "pending" | "approved" | "rejected",
    submittedAt: "May 17, 2025",
  },
  {
    id: "aq2",
    supervisee: "Marcus Chen",
    superviseeId: "sup-s2",
    initials: "MC",
    weekOf: "May 13–17, 2025",
    totalHours: 8,
    activitiesCount: 5,
    restrictedHours: 5,
    unrestrictedHours: 3,
    supervisionHours: 0,
    status: "pending" as "pending" | "approved" | "rejected",
    submittedAt: "May 18, 2025",
  },
  {
    id: "aq3",
    supervisee: "Marcus Chen",
    superviseeId: "sup-s2",
    initials: "MC",
    weekOf: "May 6–10, 2025",
    totalHours: 9,
    activitiesCount: 5,
    restrictedHours: 5.5,
    unrestrictedHours: 3.5,
    supervisionHours: 0,
    status: "pending" as "pending" | "approved" | "rejected",
    submittedAt: "May 11, 2025",
  },
  {
    id: "aq4",
    supervisee: "Sarah Mitchell",
    superviseeId: "sup-s1",
    initials: "SM",
    weekOf: "May 6–10, 2025",
    totalHours: 11,
    activitiesCount: 7,
    restrictedHours: 4,
    unrestrictedHours: 6,
    supervisionHours: 1,
    status: "approved" as "pending" | "approved" | "rejected",
    submittedAt: "May 10, 2025",
  },
]

export const supervisionSessions = [
  {
    id: "ss1",
    supervisee: "Sarah Mitchell",
    superviseeId: "sup-s1",
    initials: "SM",
    date: "May 17, 2025",
    duration: 1,
    type: "Individual",
    observationType: "Direct",
    notes: "Reviewed skill acquisition programs, discussed data trends for Client A",
    approved: true,
  },
  {
    id: "ss2",
    supervisee: "Marcus Chen",
    superviseeId: "sup-s2",
    initials: "MC",
    date: "May 16, 2025",
    duration: 1,
    type: "Individual",
    observationType: "Direct",
    notes: "FBA planning discussion, reviewed behavior protocols for new client",
    approved: true,
  },
  {
    id: "ss3",
    supervisee: "Aisha Johnson",
    superviseeId: "sup-s3",
    initials: "AJ",
    date: "May 15, 2025",
    duration: 1.5,
    type: "Individual",
    observationType: "Remote",
    notes: "Monthly check-in, reviewed unrestricted hours progress and program development",
    approved: true,
  },
  {
    id: "ss4",
    supervisee: "Sarah Mitchell",
    superviseeId: "sup-s1",
    initials: "SM",
    date: "May 10, 2025",
    duration: 1,
    type: "Group",
    observationType: "Direct",
    notes: "Group supervision — BACB ethics module review (3 trainees)",
    approved: true,
  },
  {
    id: "ss5",
    supervisee: "Marcus Chen",
    superviseeId: "sup-s2",
    initials: "MC",
    date: "May 8, 2025",
    duration: 1,
    type: "Individual",
    observationType: "Direct",
    notes: "",
    approved: false,
  },
]

export const hoursOverTime = [
  { month: "Jan", hours: 32, restricted: 13, unrestricted: 16, supervision: 3 },
  { month: "Feb", hours: 40, restricted: 17, unrestricted: 19, supervision: 4 },
  { month: "Mar", hours: 35, restricted: 19, unrestricted: 13, supervision: 3 },
  { month: "Apr", hours: 38, restricted: 16, unrestricted: 18, supervision: 4 },
  { month: "May", hours: 42.5, restricted: 18, unrestricted: 20, supervision: 4.5 },
]

export const complianceData = {
  totalHours: 423.5,
  targetHours: 1000,
  restrictedHours: 183,
  unrestrictedHours: 202,
  supervisionHours: 38.5,
  restrictedPercent: 43.2,
  supervisionPercent: 9.1,
  maxRestrictedPercent: 50,
  minSupervisionPercent: 5,
  complianceStatus: "compliant" as ComplianceStatus,
  alerts: [
    {
      type: "info" as "info" | "warning" | "error",
      message: "Supervision is above minimum (9.1% vs 5% required)",
    },
    {
      type: "info" as "info" | "warning" | "error",
      message: "576.5 hours remaining to certification",
    },
  ],
}
